# key:  [full name, short name]
venues_list = {
    'ARXIV':    ['arXiv',
                 'arXiv'],
    'JSAC':     ['IEEE Journal on Selected Areas in Communications',
                 'IEEE Journal on Selected Areas in Communications'],
    'TON':      ['IEEE/ACM Transactions on Networking',
                 'IEEE/ACM Trans. Networking'],
    'TOC':      ['IEEE Transactions on Communications',
                 'IEEE Trans. Communications'],
    'CACM':     ['Communications of the ACM',
                 'Communications of the ACM'],
    'TOCS':     ['ACM Transactions on Computer Systems',
                 'ACM Trans. Computer Systems'],
    'INM':      ['IEEE Network Magazine',
                 'IEEE Network Magazine'],
    'ITM':      ['IEEE Transactions on Multimedia',
                 'IEEE Trans. Multimedia'],
    'CCR':      ['ACM SIGCOMM Computer Communication Review',
                 'ACM SIGCOMM Computer Communication Review'],
    'TOSE':     ['ACM Transactions on Software Engineering and Methodology',
                 'ACM Trans. Software Engineering and Methodology'],
    'TOIT':     ['IEEE/ACM Transactions on Information Theory',
                 'IEEE/ACM Trans. Information Theory'],
    'LNCS':     ['Lecture Notes in Computer Science',
                 'Lecture Notes in Computer Science'],
    'ACMCHI':   ['Proceedings of the ACM Conference on Human-Computer Interaction',
                 'Proc. ACM CHI'],
    'ACMTCHI':  ['ACM Transactions on Computer-Human Interaction',
                 'ACM Trans. Computer-Human Interaction'],
    'ACMTCAD':  ['ACM Transactions on Design Automation of Electronic Systems',
                 'ACM Trans. Design Automation of Electronic Systems'],
    'DATE':     ['Proceedings of the Design Automation and Test in Europe Conference',
                 'Proc. Design Automation and Test in Europe Conf.'],
    'ICCAD':    ['Proceedings of the IEEE/ACM International Conference on Computer-Aided Design',
                 'Proc. IEEE/ACM Int. Conf. Computer-Aided Design'],
    'ICCD':     ['Proceedings of the IEEE International Conference on Computer Design',
                 'Proc. IEEE Int. Conf. Computer Design'],
    'ISSS':     ['Proceedings of the International Symposium on System Synthesis',
                 'Proc. Int. Symp. System Synthesis'],
    'TCAD':     ['IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems',
                 'IEEE Trans. Computer-Aided Design of Integrated Circuits and Systems'],
    'TVLSI':    ['IEEE Transactions on Very Large Scale Integration (VLSI) Systems',
                 'IEEE Trans. VLSI Systems'],
    'VLSI':     ['Proceedings of the International Conference on VLSI Design',
                 'Proc. Int. Conf. VLSI Design'],
    'ISIT':     ['IEEE International Symposium on Information Theory',
                 'IEEE Int. Symp. Information Theory'],
    'ITIT':     ['IEEE Transactions on Information Theory',
                 'IEEE Trans. Information Theory'],
    'ALLERTON': ['Proceedings of the Annual Allerton Conference on Communication, Control, and Computing',
                 'Proc. Annual Allerton Conf. Communication, Control, and Computing'],
    'ASILOMAR': ['Proceedings of the IEEE Asilomar Conference on Signals, Systems, and Computers',
                 'Proc. IEEE ACSSC'],
    'ASPLOS':   ['Proceedings of the ACM International Conference on Architectural Support for Programming Languages and Operating Systems',
                 'Proc. ACM ASPLOS'],
    'BSN':      ['Proceedings of the IEEE International Workshop on Wearable and Implantable Body Sensor Networks',
                 'Proc. IEEE Workshp. BSN'],
    'CASES':    ['Proceedings of the International Conference on Compilers, Architecture, and Synthesis for Embedded Systems',
                 'Proc. CASES'],
    'CISS':     ['Proceedings of the Annual Conference on Information Sciences and Systems',
                 'Proc. Annual CISS'],
    'CONEXT':   ['Proceedings of the International Conference on emerging Networking EXperiments and Technologies',
                 'Proc. CoNXET'],
    'CDC':      ['Proceedings of the IEEE Conference on Decision and Control',
                 'Proc. IEEE CDC'],
    'DYSPAN':   ['Proceedings of the IEEE International Symposium on Dynamic Spectrum Access Networks',
                 'Proc. IEEE DySPAN'],
    'DAC':      ['Proceedings of the ACM/IEEE Design Automation Conference',
                 'Proc. ACM/IEEE DAC'],
    'DSN':      ['Proceedings of the IEEE/IFIP International Conference on Dependable Systems and Networks',
                 'Proc. IEEE/IFIP DSN'],
    'GLOBECOM': ['Proceedings of the IEEE Global Communications Conference',
                 'Proc. IEEE GLOBECOM'],
    'HOTMOBILE':['Proceedings of the ACM Workshop on Hot Topics in Mobile Computing Systems and Applications',
                 'Proc. ACM Workshp. HotMobile'],
    'HOTNETS':  ['Proceedings of the ACM Workshop on Hot Topics in Networks',
                 'Proc. ACM Workshp. HotNets'],
    'HOTOS':    ['Proceedings of the Workshop on Hot Topics in Operating Systems',
                 'Proc. Workshp. HotOS'],
    'HOTPOWER': ['Proceedings of the Workshop on Power-Aware Computing and Systems',
                 'Proc. Workshp. HotPower'],
    'ICDCS':    ['Proceedings of the IEEE International Conference on Distributed Computing Systems',
                 'Proc. IEEE ICDCS'],
    'IMC':      ['Proceedings of the ACM Internet Measurement Conference',
                 'Proc. ACM IMC'],
    'INFOCOM':  ['Proceedings of the IEEE International Conference on Computer Communications',
                 'Proc. IEEE INFOCOM'],
    'ISCAS':    ['Proceedings of the IEEE International Symposium on Circuits and Systems',
                 'Proc. IEEE ISCAS'],
    'ISCC':     ['Proceedings of the IEEE International Symposium on Computers and Communications',
                 'Proc. IEEE ISCC'],
    'ISLPED':   ['Proceedings of the ACM/IEEE International Symposium on Low Power Electronics and Design',
                 'Proc. ACM/IEEE ISLPED'],
    'ISSPA':    ['Proceedings of the IEEE International Conference on Information Sciences, Signal Processing and their Applications',
                 'Proc. IEEE ISSPA'],
    'ISWC':     ['Proceedings of the IEEE International Symposium on Wearable Computers',
                 'Proc. IEEE ISWC'],
    'IWQOS':    ['Proceedings of the IEEE/ACM International Workshop on Quality of Service',
                 'Proc. IEEE/ACM IWQoS'],
    'MASCOTS':  ['Proceedings of the IEEE International Symposium on Modeling, Analysis, and Simulation of Computer and Telecommunication Systems',
                 'Proc. IEEE MASCOTS'],
    'MILCOM':   ['Proceedings of the IEEE Military Communications Conference',
                 'Proc. IEEE MILCOM'],
    'MOBICOM':  ['Proceedings of the ACM International Conference on Mobile Computing and Networking',
                 'Proc. ACM MobiCom'],
    'MOBISYS':  ['Proceedings of the ACM International Conference on Mobile Systems, Applications, and Services',
                 'Proc. ACM MobiSys'],
    'MOBI-EVAL':['Proceedings of the ACM Workshop on Mobile Computing Systems and Applications Evaluation',
                 'Proc. ACM MobEval'],
    'MOBIHOC':  ['Proceedings of the ACM International Symposium on Mobile Ad Hoc Networking and Computing',
                 'Proc. ACM MobiHoc'],
    'MOBILEHCI':['Proceedings of the ACM International Conference on Human-Computer Interaction with Mobile Devices and Services',
                 'Proc. ACM MobileHCI'],
    'MOMUC':    ['Proceedings of the International Workshop on Mobile Multimedia Communications',
                 'Proc. Int. Workshp. MoMuC'],
    'MULTIMEDIA':['Proceedings of the ACM International Conference on Multimedia',
                 'Proc. ACM Multimedia'],
    'NSDI':     ['Proceedings of the USENIX Symposium on Networked Systems Design and Implementation',
                 'Proc. USENIX NSDI'],
    'OSDI':     ['Proceedings of the USENIX Symposium on Operating Systems Design and Implementation',
                 'Proc. USENIX OSDI'],
    'PERCOM':   ['Proceedings of the IEEE International Conference on Pervasive Computing and Communications',
                 'Proc. IEEE PerCom'],
    'PIMRC':    ['Proceedings of the IEEE International Symposium on Personal, Indoor, and Mobile Radio Communications',
                 'Proc. IEEE PIMRC'],
    'RAWCON':   ['Proceedings of the IEEE Radio and Wireless Conference',
                 'Proc. IEEE RAWCON'],
    'SECON':    ['Proceedings of the IEEE/ACM International Conference on Sensing, Communication, and Networking',
                 'Proc. IEEE/ACM SECON'],
    'SENSYS':   ['Proceedings of the ACM Conference on Embedded Networked Sensor Systems',
                 'Proc. ACM SenSys'],
    'SIGMETRICS':['Proceedings of the ACM International Conference on Measurement and Modeling of Computer Systems',
                 'Proc. ACM SIGMETRICS'],
    'SIGCOMM':  ['Proceedings of the ACM SIGCOMM Conference on Applications, Technologies, Architectures, and Protocols for Computer Communication',
                 'Proc. ACM SIGCOMM'],
    'SP':       ['Proceedings of the IEEE Symposium on Security and Privacy',
                 'Proc. IEEE SP'],
    'EMSOFT':   ['Proceedings of the ACM International Conference on Embedded Software',
                 'Proc. ACM EMSOFT'],
    'SOSP':     ['Proceedings of the ACM Symposium on Operating Systems Principles',
                 'Proc. ACM SOSP'],
    'ATC':      ['Proceedings of the USENIX Annual Technical Conference',
                 'Proc. USENIX ATC'],
    'UIST':     ['Proceedings of the ACM Symposium on User Interface Software and Technology',
                 'Proc. ACM UIST'],
    'UBICOMP':  ['Proceedings of the ACM International Joint Conference on Pervasive and Ubiquitous Computing',
                 'Proc. ACM UbiComp'],
    'VTC':      ['Proceedings of the IEEE Vehicular Technology Conference',
                 'Proc. IEEE VTC'],
    'WCNC':     ['Proceedings of the IEEE Wireless Communications and Networking Conference',
                 'Proc. IEEE WCNC'],
    'WICON':    ['Proceedings of the International Wireless Internet Conference',
                 'Proc. Int. WICON'],
    'WINMEE':   ['Proceedings of the International Workshop on Wireless Network Measurements',
                 'Proc. Int. Workshp. WinMee'],
    'WISE':     ['Proceedings of the ACM Workshop on Wireless Security (WiSe)',
                 'Proc. ACM WiSe'],
    'WISEC':    ['Proceedings of the ACM Conference on Security and Privacy in Wireless and Mobile Networks',
                 'Proc. ACM WiSec'],
    'CCS':      ['Proceedings of the ACM Conference on Computer and Communications Security',
                 'Proc. ACM CCS'],
    'ISCA':     ['Proceedings of the ACM/IEEE International Symposium on Computer Architecture',
                 'Proc. ACM/IEEE ISCA'],
    'IPDPS':    ['Proceedings of the IEEE International Parallel and Distributed Processing Symposium',
                 'Proc. IEEE IPDPS'],
    'PACT':     ['Proceedings of the International Conference on Parallel Architectures and Compilation Techniques',
                 'Proc. Int. Conf. PACT'],
    'WWW':      ['Proceedings of the International World Wide Web Conference',
                 'Proc. Int. WWW'],
    'HOTPAR':   ['Proceedings of the USENIX Workshop on Hot Topics in Parallelism',
                 'Proc. USENIX Workshp. HotPar'],
    'EUROSYS':  ['Proceedings of the ACM European Conference on Computer Systems',
                 'Proc. ACM EuroSys'],
    'SC':       ['Proceedings of the ACM/IEEE International Conference on High Performance Computing, Networking, Storage and Analysis',
                 'Proc. ACM/IEEE SC'],
    'ISSCC':    ['Proceedings of the IEEE International Solid-State Circuits Conference',
                 'Proc. IEEE ISSCC'],
    'VLDB':     ['Proceedings of the International Conference on Very Large Data Bases',
                 'Proc. Int. Conf. VLDB'],
    'PLDI':     ['Proceedings of the ACM SIGPLAN Conference on Programming Language Design and Implementation',
                 'Proc. ACM PLDI'],
    'VEE':      ['Proceedings of the ACM SIGPLAN/SIGOPS Conference on Virtual Execution Environments',
                 'Proc. ACM VEE'],
    'MICRO':    ['Proceedings of the IEEE/ACM International Symposium on Microarchitecture',
                 'Proc. IEEE/ACM MICRO'],
    'OOPSLA':   ['Proceedings of the ACM Conference on Object-Oriented Programming Systems, Languages, and Applications',
                 'Proc. ACM OOPSLA'],
    'IPSN':     ['Proceedings of the ACM/IEEE International Conference on Information Processing in Sensor Networks',
                 'Proc. ACM/IEEE IPSN'],
    'POPL':     ['Proceedings of ACM SIGPLAN-SIGACT Symposium on Principles of Programming Languages (POPL)',
                 'Proc. ACM POPL'],
    'BALTZER':  ['Wireless Networks Journal published by Baltzer',
                 'Wireless Networks Journal published by Baltzer'],
    'TIT':      ['IEEE Transactions on Information Theory',
                 'IEEE Trans. Information Theory'],
    'TCOMM':    ['IEEE Transactions on Communications',
                 'IEEE Trans. Communications'],
    'TWC':      ['IEEE Transactions on Wireless Communications',
                 'IEEE Trans. Wireless Communications'],
    'TCOMP':    ['IEEE Transactions on Computers',
                 'IEEE Trans. Computers'],
    'TMC':      ['IEEE Transactions on Mobile Computing',
                 'IEEE Trans. Mobile Computing'],
    'SIAMCOMP': ['SIAM Journal on Computing',
                 'SIAM Journal on Computing'],
    'EURASIP':  ['EURASIP Journal on Applied Signal Processing',
                 'EURASIP Journal on Applied Signal Processing'],
    'TSIG':     ['IEEE Transactions on Signal Processing',
                 'IEEE Trans. Signal Processing'],
    'ICSE':     ['Proceedings of the ACM/IEEE International Conference on Software Engineering',
                 'Proc. ACM/IEEE ICSE'],
    'ASE':      ['Proceedings of the IEEE/ACM International Conference on Automated Software Engineering (ASE)',
                 'Proc. IEEE/ACM ASE'],
    'FSE':      ['Proceedings of the ACM SIGSOFT Symposium on the Foundations of Software Engineering (FSE)',
                 'Proc. ACM FSE'],
}