venues_list = {
    'ARXIV': 'arXiv',
    'JSAC': 'IEEE Journal on Selected Areas in Communications',
    'TON': 'IEEE/ACM Transactions on Networking',
    'TOC': 'IEEE Transactions on Communications',
    'CACM': 'Communications of the ACM',
    'TOCS': 'ACM Transactions on Computer Systems',
    'INM': 'IEEE Network Magazine',
    'ITM': 'IEEE Transactions on Multimedia',
    'CCR': 'ACM SIGCOMM Computer Communication Review',
    'TOSE': 'ACM Transactions on Software Engineering and Methodology',
    'TOIT': 'IEEE/ACM Transactions on Information Theory',
    'LNCS': 'Lecture Notes in Computer Science',
    'ACMCHI': 'Proceedings of the ACM Conference on Human-Computer Interaction',
    'ACMTCHI': 'ACM Transactions on Computer-Human Interaction',
    'ACMTCAD': 'ACM Transactions on Design Automation of Electronic Systems',
    'DATE': 'Proceedings of the Design Automation and Test in Europe Conference',
    'ICCAD': 'Proceedings of the IEEE/ACM International Conference on Computer-Aided Design',
    'ICCD': 'Proceedings of the IEEE International Conference on Computer Design',
    'ISSS': 'Proceedings of the International Symposium on System Synthesis',
    'TCAD': 'IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems',
    'TVLSI': 'IEEE Transactions on Very Large Scale Integration (VLSI) Systems',
    'VLSI': 'Proceedings of the International Conference on VLSI Design',
    'ISIT': 'IEEE International Symposium on Information Theory',
    'ITIT': 'IEEE Transactions on Information Theory',
    'ALLERTON': 'Proceedings of the Annual Allerton Conference on Communication, Control, and Computing',
    'ASILOMAR': 'Proceedings of the IEEE Asilomar Conference on Signals, Systems, and Computers',
    'ASPLOS': 'Proceedings of the ACM International Conference on Architectural Support for Programming Languages and Operating Systems',
    'BSN': 'Proceedings of the IEEE International Workshop on Wearable and Implantable Body Sensor Networks',
    'CASES': 'Proceedings of the International Conference on Compilers, Architecture, and Synthesis for Embedded Systems',
    'CISS': 'Proceedings of the Annual Conference on Information Sciences and Systems',
    'CONEXT': 'Proceedings of the International Conference on emerging Networking EXperiments and Technologies',
    'CDC': 'Proceedings of the IEEE Conference on Decision and Control',
    'DYSPAN': 'Proceedings of the IEEE International Symposium on Dynamic Spectrum Access Networks',
    'DAC': 'Proceedings of the ACM/IEEE Design Automation Conference',
    'DSN': 'Proceedings of the IEEE/IFIP International Conference on Dependable Systems and Networks',
    'GLOBECOM': 'Proceedings of the IEEE Global Communications Conference',
    'HOTMOBILE': 'Proceedings of the ACM Workshop on Hot Topics in Mobile Computing Systems and Applications',
    'HOTNETS': 'Proceedings of the ACM Workshop on Hot Topics in Networks',
    'HOTOS': 'Proceedings of the Workshop on Hot Topics in Operating Systems',
    'HOTPOWER': 'Proceedings of the Workshop on Power-Aware Computing and Systems',
    'ICDCS': 'Proceedings of the IEEE International Conference on Distributed Computing Systems',
    'IMC': 'Proceedings of the ACM Internet Measurement Conference',
    'INFOCOM': 'Proceedings of the IEEE International Conference on Computer Communications',
    'ISCAS': 'Proceedings of the IEEE International Symposium on Circuits and Systems',
    'ISCC': 'Proceedings of the IEEE International Symposium on Computers and Communications',
    'ISLPED': 'Proceedings of the ACM/IEEE International Symposium on Low Power Electronics and Design',
    'ISSPA': 'Proceedings of the IEEE International Conference on Information Sciences, Signal Processing and their Applications',
    'ISWC': 'Proceedings of the IEEE International Symposium on Wearable Computers',
    'IWQOS': 'Proceedings of the IEEE/ACM International Workshop on Quality of Service',
    'MASCOTS': 'Proceedings of the IEEE International Symposium on Modeling, Analysis, and Simulation of Computer and Telecommunication Systems',
    'MILCOM': 'Proceedings of the IEEE Military Communications Conference',
    'MOBICOM': 'Proceedings of the ACM International Conference on Mobile Computing and Networking',
    'MOBISYS': 'Proceedings of the ACM International Conference on Mobile Systems, Applications, and Services',
    'MOBI-EVAL': 'Proceedings of the ACM Workshop on Mobile Computing Systems and Applications Evaluation',
    'MOBIHOC': 'Proceedings of the ACM International Symposium on Mobile Ad Hoc Networking and Computing',
    'MOBILEHCI': 'Proceedings of the ACM International Conference on Human-Computer Interaction with Mobile Devices and Services',
    'MOMUC': 'Proceedings of the International Workshop on Mobile Multimedia Communications',
    'MULTIMEDIA': 'Proceedings of the ACM International Conference on Multimedia',
    'NSDI': 'Proceedings of the USENIX Symposium on Networked Systems Design and Implementation',
    'OSDI': 'Proceedings of the USENIX Symposium on Operating Systems Design and Implementation',
    'PERCOM': 'Proceedings of the IEEE International Conference on Pervasive Computing and Communications',
    'PIMRC': 'Proceedings of the IEEE International Symposium on Personal, Indoor, and Mobile Radio Communications',
    'RAWCON': 'Proceedings of the IEEE Radio and Wireless Conference',
    'SECON': 'Proceedings of the IEEE/ACM International Conference on Sensing, Communication, and Networking',
    'SENSYS': 'Proceedings of the ACM Conference on Embedded Networked Sensor Systems',
    'SIGMETRICS': 'Proceedings of the ACM International Conference on Measurement and Modeling of Computer Systems',
    'SIGCOMM': 'Proceedings of the ACM SIGCOMM Conference on Applications, Technologies, Architectures, and Protocols for Computer Communication',
    'SP': 'Proceedings of the IEEE Symposium on Security and Privacy',
    'EMSOFT': 'Proceedings of the ACM International Conference on Embedded Software',
    'SOSP': 'Proceedings of the ACM Symposium on Operating Systems Principles',
    'ATC': 'Proceedings of the USENIX Annual Technical Conference',
    'UIST': 'Proceedings of the ACM Symposium on User Interface Software and Technology',
    'UBICOMP': 'Proceedings of the ACM International Joint Conference on Pervasive and Ubiquitous Computing',
    'VTC': 'Proceedings of the IEEE Vehicular Technology Conference',
    'WCNC': 'Proceedings of the IEEE Wireless Communications and Networking Conference',
    'WICON': 'Proceedings of the International Wireless Internet Conference',
    'WINMEE': 'Proceedings of the International Workshop on Wireless Network Measurements',
    'WISE': 'Proceedings of the ACM Workshop on Wireless Security (WiSe)',
    'WISEC': 'Proceedings of the ACM Conference on Security and Privacy in Wireless and Mobile Networks',
    'CCS': 'Proceedings of the ACM Conference on Computer and Communications Security',
    'ISCA': 'Proceedings of the ACM/IEEE International Symposium on Computer Architecture',
    'IPDPS': 'Proceedings of the IEEE International Parallel and Distributed Processing Symposium',
    'PACT': 'Proceedings of the International Conference on Parallel Architectures and Compilation Techniques',
    'WWW': 'Proceedings of the International World Wide Web Conference',
    'HOTPAR': 'Proceedings of the USENIX Workshop on Hot Topics in Parallelism',
    'EUROSYS': 'Proceedings of the ACM European Conference on Computer Systems',
    'SC': 'Proceedings of the ACM/IEEE International Conference on High Performance Computing, Networking, Storage and Analysis',
    'ISSCC': 'Proceedings of the IEEE International Solid-State Circuits Conference',
    'VLDB': 'Proceedings of the International Conference on Very Large Data Bases',
    'PLDI': 'Proceedings of the ACM SIGPLAN Conference on Programming Language Design and Implementation',
    'VEE': 'Proceedings of the ACM SIGPLAN/SIGOPS Conference on Virtual Execution Environments',
    'MICRO': 'Proceedings of the IEEE/ACM International Symposium on Microarchitecture',
    'OOPSLA': 'Proceedings of the ACM Conference on Object-Oriented Programming Systems, Languages, and Applications',
    'IPSN': 'Proceedings of the ACM/IEEE International Conference on Information Processing in Sensor Networks',
    'POPL': 'Proceedings of ACM SIGPLAN-SIGACT Symposium on Principles of Programming Languages',
    'BALTZER': 'Wireless Networks Journal published by Baltzer',
    'TIT': 'IEEE Transactions on Information Theory',
    'TCOMM': 'IEEE Transactions on Communications',
    'TWC': 'IEEE Transactions on Wireless Communications',
    'TCOMP': 'IEEE Transactions on Computers',
    'TMC': 'IEEE Transactions on Mobile Computing',
    'SIAMCOMP': 'SIAM Journal on Computing',
    'EURASIP': 'EURASIP Journal on Applied Signal Processing',
    'TSIG': 'IEEE Transactions on Signal Processing',
    'ICSE': 'Proceedings of the ACM/IEEE International Conference on Software Engineering',
    'ASE': 'Proceedings of the IEEE/ACM International Conference on Automated Software Engineering',
    'FSE': 'Proceedings of the ACM SIGSOFT Symposium on the Foundations of Software Engineering',
}