# key:  [full name, short name]
venues_list = {
    'ARXIV':    ['arXiv',
                 'arXiv'],
    'JSAC':     ['IEEE Journal on Selected Areas in Communications',
                 'IEEE Journal on Selected Areas in Communications'],
    'TON':      ['IEEE/ACM Transactions on Networking',
                 'IEEE/ACM Transactions on Networking'],
    'TOC':      ['IEEE Transactions on Communications',
                 'IEEE Transactions on Communications'],
    'CACM':     ['Communications of the ACM',
                 'Communications of the ACM'],
    'TOCS':     ['ACM Transactions on Computer Systems',
                 'ACM Transactions on Computer Systems'],
    'INM':      ['IEEE Network Magazine',
                 'IEEE Network Magazine'],
    'ITM':      ['IEEE Transactions on Multimedia',
                 'IEEE Transactions on Multimedia'],
    'CCR':      ['ACM SIGCOMM Computer Communication Review',
                 'ACM SIGCOMM Computer Communication Review'],
    'TOSE':     ['ACM Transactions on Software Engineering and Methodology',
                 'ACM Transactions on Software Engineering and Methodology'],
    'TOIT':     ['IEEE/ACM Transactions on Information Theory',
                 'IEEE/ACM Transactions on Information Theory'],
    'LNCS':     ['Lecture Notes in Computer Science',
                 'Lecture Notes in Computer Science'],
    'ACMCHI':   ['Proceedings of the ACM Conference on Human-Computer Interaction',
                 'Proc. ACM Conference on Human-Computer Interaction'],
    'ACMTCHI':  ['ACM Transactions on Computer-Human Interaction',
                 'ACM Transactions on Computer-Human Interaction'],
    'ACMTCAD':  ['ACM Transactions on Design Automation of Electronic Systems',
                 'ACM Transactions on Design Automation of Electronic Systems'],
    'DATE':     ['Proceedings of the Design Automation and Test in Europe Conference',
                 'Proc. Design Automation and Test in Europe Conference'],
    'ICCAD':    ['Proceedings of the IEEE/ACM International Conference on Computer-Aided Design',
                 'Proc. IEEE/ACM Int. Conference on Computer-Aided Design'],
    'ICCD':     ['Proceedings of the IEEE International Conference on Computer Design',
                 'Proc. IEEE Int. Conference on Computer Design'],
    'ISSS':     ['Proceedings of the International Symposium on System Synthesis',
                 'Proc. Int. Symp. on System Synthesis'],
    'TCAD':     ['IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems',
                 'IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems'],
    'TVLSI':    ['IEEE Transactions on Very Large Scale Integration (VLSI) Systems',
                 'IEEE Transactions on Very Large Scale Integration (VLSI) Systems'],
    'VLSI':     ['Proceedings of the International Conference on VLSI Design',
                 'Proc. Int. Conference on VLSI Design'],
    'ISIT':     ['IEEE International Symposium on Information Theory',
                 'IEEE Int. Symp. on Information Theory'],
    'ITIT':     ['IEEE Transactions on Information Theory',
                 'IEEE Transactions on Information Theory'],
    'ALLERTON': ['Proceedings of the Annual Allerton Conference on Communication, Control, and Computing',
                 'Proc. Annual Allerton Conference on Communication, Control, and Computing'],
    'ASILOMAR': ['Proceedings of the IEEE Asilomar Conference on Signals, Systems, and Computers (ACSSC)',
                 'Proc. IEEE Asilomar Conference on Signals, Systems, and Computers (ACSSC)'],
    'ASPLOS':   ['Proceedings of the ACM International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS)',
                 'Proc. ACM Int. Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS)'],
    'BSN':      ['Proceedings of the IEEE International Workshop on Wearable and Implantable Body Sensor Networks (BSN)',
                 'Proc. IEEE Int. Workshop on Wearable and Implantable Body Sensor Networks (BSN)'],
    'CASES':    ['Proceedings of the International Conference on Compilers, Architecture, and Synthesis for Embedded Systems (CASES)',
                 'Proc. Int. Conference on Compilers, Architecture, and Synthesis for Embedded Systems (CASES)'],
    'CISS':     ['Proceedings of the Annual Conference on Information Sciences and Systems (CISS)',
                 'Proc. Annual Conference on Information Sciences and Systems (CISS)'],
    'CONEXT':   ['Proceedings of the International Conference on Emerging Networking Experiments and Technologies (CoNEXT)',
                 'Proc. Int. Conference on Emerging Networking Experiments and Technologies (CoNEXT)'],
    'CDC':      ['Proceedings of the IEEE Conference on Decision and Control (CDC)',
                 'Proc. IEEE Conference on Decision and Control (CDC)'],
    'DYSPAN':   ['Proceedings of the IEEE International Symposium on Dynamic Spectrum Access Networks (DySPAN)',
                 'Proc. IEEE Int. Symp. on Dynamic Spectrum Access Networks (DySPAN)'],
    'DAC':      ['Proceedings of the ACM/IEEE Design Automation Conference (DAC)',
                 'Proc. ACM/IEEE Design Automation Conference (DAC)'],
    'DSN':      ['Proceedings of the IEEE/IFIP International Conference on Dependable Systems and Networks (DSN)',
                 'Proc. IEEE/IFIP Int. Conference on Dependable Systems and Networks (DSN)'],
    'GLOBECOM': ['Proceedings of the IEEE Global Communications Conference (GLOBECOM)',
                 'Proc. IEEE Global Communications Conference (GLOBECOM)'],
    'HOTMOBILE':['Proceedings of the ACM Workshop on Hot Topics in Mobile Computing Systems and Applications (HotMobile)',
                 'Proc. ACM Workshop on Hot Topics in Mobile Computing Systems and Applications (HotMobile)'],
    'HOTNETS':  ['Proceedings of the ACM Workshop on Hot Topics in Networks (HotNets)',
                 'Proc. ACM Workshop on Hot Topics in Networks (HotNets)'],
    'HOTOS':    ['Proceedings of the Workshop on Hot Topics in Operating Systems (HotOS)',
                 'Proc. Workshop on Hot Topics in Operating Systems (HotOS)'],
    'HOTPOWER': ['Proceedings of the Workshop on Power-Aware Computing and Systems (HotPower)',
                 'Proc. Workshop on Power-Aware Computing and Systems (HotPower)'],
    'ICDCS':    ['Proceedings of the IEEE International Conference on Distributed Computing Systems (ICDCS)',
                 'Proc. IEEE Int. Conference on Distributed Computing Systems (ICDCS)'],
    'IMC':      ['Proceedings of the ACM Internet Measurement Conference (IMC)',
                 'Proc. ACM Internet Measurement Conference (IMC)'],
    'INFOCOM':  ['Proceedings of the IEEE International Conference on Computer Communications (INFOCOM)',
                 'Proc. IEEE Int. Conference on Computer Communications (INFOCOM)'],
    'ISCAS':    ['Proceedings of the IEEE International Symposium on Circuits and Systems (ISCAS)',
                 'Proc. IEEE Int. Symp. on Circuits and Systems (ISCAS)'],
    'ISCC':     ['Proceedings of the IEEE International Symposium on Computers and Communications (ISCC)',
                 'Proc. IEEE Int. Symp. on Computers and Communications (ISCC)'],
    'ISLPED':   ['Proceedings of the ACM/IEEE International Symposium on Low Power Electronics and Design (ISLPED)',
                 'Proc. ACM/IEEE Int. Symp. on Low Power Electronics and Design (ISLPED)'],
    'ISSPA':    ['Proceedings of the IEEE International Conference on Information Sciences, Signal Processing and their Applications (ISSPA)',
                 'Proc. IEEE Int. Conference on Information Sciences, Signal Processing and their Applications (ISSPA)'],
    'ISWC':     ['Proceedings of the IEEE International Symposium on Wearable Computers (ISWC)',
                 'Proc. IEEE Int. Symp. on Wearable Computers (ISWC)'],
    'IWQOS':    ['Proceedings of the IEEE/ACM International Workshop on Quality of Service (IWQoS)',
                 'Proc. IEEE/ACM Int. Workshop on Quality of Service (IWQoS)'],
    'MASCOTS':  ['Proceedings of the IEEE International Symposium on Modeling, Analysis, and Simulation of Computer and Telecommunication Systems (MASCOTS)',
                 'Proc. IEEE Int. Symp. on Modeling, Analysis, and Simulation of Computer and Telecommunication Systems (MASCOTS)'],
    'MILCOM':   ['Proceedings of the IEEE Military Communications Conference (MILCOM)',
                 'Proc. IEEE Military Communications Conference (MILCOM)'],
    'MOBICOM':  ['Proceedings of the ACM International Conference on Mobile Computing and Networking (MobiCom)',
                 'Proc. ACM Int. Conference on Mobile Computing and Networking (MobiCom)'],
    'MOBISYS':  ['Proceedings of the ACM International Conference on Mobile Systems, Applications, and Services (MobiSys)',
                 'Proc. ACM Int. Conference on Mobile Systems, Applications, and Services (MobiSys)'],
    'MOBI-EVAL':['Proceedings of the ACM Workshop on Mobile Computing Systems and Applications Evaluation (MobEval)',
                 'Proc. ACM Workshop on Mobile Computing Systems and Applications Evaluation (MobEval)'],
    'MOBIHOC':  ['Proceedings of the ACM International Symposium on Mobile Ad Hoc Networking and Computing (MobiHoc)',
                 'Proc. ACM Int. Symp. on Mobile Ad Hoc Networking and Computing (MobiHoc)'],
    'MOBILEHCI':['Proceedings of the ACM International Conference on Human-Computer Interaction with Mobile Devices and Services (MobileHCI)',
                 'Proc. ACM Int. Conference on Human-Computer Interaction with Mobile Devices and Services (MobileHCI)'],
    'MOMUC':    ['Proceedings of the International Workshop on Mobile Multimedia Communications (MoMuC)',
                 'Proc. Int. Workshop on Mobile Multimedia Communications (MoMuC)'],
    'MULTIMEDIA':['Proceedings of the ACM International Conference on Multimedia (Multimedia)',
                 'Proc. ACM Int. Conference on Multimedia (Multimedia)'],
    'NSDI':     ['Proceedings of the USENIX Symposium on Networked Systems Design and Implementation (NSDI)',
                 'Proc. USENIX Symp. on Networked Systems Design and Implementation (NSDI)'],
    'OSDI':     ['Proceedings of the USENIX Symposium on Operating Systems Design and Implementation (OSDI)',
                 'Proc. USENIX Symp. on Operating Systems Design and Implementation (OSDI)'],
    'PERCOM':   ['Proceedings of the IEEE International Conference on Pervasive Computing and Communications (PerCom)',
                 'Proc. IEEE Int. Conference on Pervasive Computing and Communications (PerCom)'],
    'PIMRC':    ['Proceedings of the IEEE International Symposium on Personal, Indoor, and Mobile Radio Communications (PIMRC)',
                 'Proc. IEEE Int. Symp. on Personal, Indoor, and Mobile Radio Communications (PIMRC)'],
    'RAWCON':   ['Proceedings of the IEEE Radio and Wireless Conference (RAWCON)',
                 'Proc. IEEE Radio and Wireless Conference (RAWCON)'],
    'SECON':    ['Proceedings of the IEEE/ACM International Conference on Sensing, Communication, and Networking (SECON)',
                 'Proc. IEEE/ACM Int. Conference on Sensing, Communication, and Networking (SECON)'],
    'SENSYS':   ['Proceedings of the ACM Conference on Embedded Networked Sensor Systems (SenSys)',
                 'Proc. ACM Conference on Embedded Networked Sensor Systems (SenSys)'],
    'SIGMETRICS':['Proceedings of the ACM International Conference on Measurement and Modeling of Computer Systems (SIGMETRICS)',
                 'Proc. ACM Int. Conference on Measurement and Modeling of Computer Systems (SIGMETRICS)'],
    'SIGCOMM':  ['Proceedings of the ACM SIGCOMM Conference on Applications, Technologies, Architectures, and Protocols for Computer Communication (SIGCOMM)',
                 'Proc. ACM SIGCOMM Conference on Applications, Technologies, Architectures, and Protocols for Computer Communication (SIGCOMM)'],
    'SP':       ['Proceedings of the IEEE Symposium on Security and Privacy (SP)',
                 'Proc. IEEE Symp. on Security and Privacy (SP)'],
    'EMSOFT':   ['Proceedings of the ACM International Conference on Embedded Software (EMSOFT)',
                 'Proc. ACM Int. Conference on Embedded Software (EMSOFT)'],
    'SOSP':     ['Proceedings of the ACM Symposium on Operating Systems Principles (SOSP)',
                 'Proc. ACM Symp. on Operating Systems Principles (SOSP)'],
    'ATC':      ['Proceedings of the USENIX Annual Technical Conference (ATC)',
                 'Proc. USENIX Annual Technical Conference (ATC)'],
    'UIST':     ['Proceedings of the ACM Symposium on User Interface Software and Technology (UIST)',
                 'Proc. ACM Symp. on User Interface Software and Technology (UIST)'],
    'UBICOMP':  ['Proceedings of the ACM International Joint Conference on Pervasive and Ubiquitous Computing (UbiComp)',
                 'Proc. ACM Int. Joint Conference on Pervasive and Ubiquitous Computing (UbiComp)'],
    'VTC':      ['Proceedings of the IEEE Vehicular Technology Conference (VTC)',
                 'Proc. IEEE Vehicular Technology Conference (VTC)'],
    'WCNC':     ['Proceedings of the IEEE Wireless Communications and Networking Conference (WCNC)',
                 'Proc. IEEE Wireless Communications and Networking Conference (WCNC)'],
    'WICON':    ['Proceedings of the International Wireless Internet Conference (WICON)',
                 'Proc. Int. Wireless Internet Conference (WICON)'],
    'WINMEE':   ['Proceedings of the International Workshop on Wireless Network Measurements (WinMee)',
                 'Proc. Int. Workshop on Wireless Network Measurements (WinMee)'],
    'WISE':     ['Proceedings of the ACM Workshop on Wireless Security (WiSec)',
                 'Proc. ACM Workshop on Wireless Security (WiSec)'],
    'WISEC':    ['Proceedings of the ACM Conference on Wireless Network Security (WiSec)',
                 'Proc. ACM Conference on Wireless Network Security (WiSec)'],
    'CCS':      ['Proceedings of the ACM Conference on Computer and Communications Security (CCS)',
                 'Proc. ACM Conference on Computer and Communications Security (CCS)'],
    'ISCA':     ['Proceedings of the ACM/IEEE International Symposium on Computer Architecture (ISCA)',
                 'Proc. ACM/IEEE Int. Symp. on Computer Architecture (ISCA)'],
    'IPDPS':    ['Proceedings of the IEEE International Parallel and Distributed Processing Symposium (IPDPS)',
                 'Proc. IEEE Int. Parallel and Distributed Processing Symp. (IPDPS)'],
    'PACT':     ['Proceedings of the International Conference on Parallel Architectures and Compilation Techniques (PACT)',
                 'Proc. Int. Conference on Parallel Architectures and Compilation Techniques (PACT)'],
    'WWW':      ['Proceedings of the International World Wide Web Conference (WWW)',
                 'Proc. Int. World Wide Web Conference (WWW)'],
    'HOTPAR':   ['Proceedings of the USENIX Workshop on Hot Topics in Parallelism (HotPar)',
                 'Proc. USENIX Workshop on Hot Topics in Parallelism (HotPar)'],
    'EUROSYS':  ['Proceedings of the ACM European Conference on Computer Systems (EuroSys)',
                 'Proc. ACM European Conference on Computer Systems (EuroSys)'],
    'SC':       ['Proceedings of the ACM/IEEE International Conference on High Performance Computing, Networking, Storage and Analysis (SC)',
                 'Proc. ACM/IEEE Int. Conference on High Performance Computing, Networking, Storage and Analysis (SC)'],
    'ISSCC':    ['Proceedings of the IEEE International Solid-State Circuits Conference (ISSCC)',
                 'Proc. IEEE Int. Solid-State Circuits Conference (ISSCC)'],
    'VLDB':     ['Proceedings of the International Conference on Very Large Data Bases (VLDB)',
                 'Proc. Int. Conference on Very Large Data Bases (VLDB)'],
    'PLDI':     ['Proceedings of the ACM SIGPLAN Conference on Programming Language Design and Implementation (PLDI)',
                 'Proc. ACM SIGPLAN Conference on Programming Language Design and Implementation (PLDI)'],
    'VEE':      ['Proceedings of the ACM SIGPLAN/SIGOPS Conference on Virtual Execution Environments (VEE)',
                 'Proc. ACM SIGPLAN/SIGOPS Conference on Virtual Execution Environments (VEE)'],
    'MICRO':    ['Proceedings of the IEEE/ACM International Symposium on Microarchitecture (MICRO)',
                 'Proc. IEEE/ACM Int. Symp. on Microarchitecture (MICRO)'],
    'OOPSLA':   ['Proceedings of the ACM Conference on Object-Oriented Programming Systems, Languages, and Applications (OOPSLA)',
                 'Proc. ACM Conference on Object-Oriented Programming Systems, Languages, and Applications (OOPSLA)'],
    'IPSN':     ['Proceedings of the ACM/IEEE International Conference on Information Processing in Sensor Networks (IPSN)',
                 'Proc. ACM/IEEE Int. Conference on Information Processing in Sensor Networks (IPSN)'],
    'POPL':     ['Proc. of the ACM SIGPLAN-SIGACT Symposium on Principles of Programming Languages (POPL)',
                 'Proc. of the ACM SIGPLAN-SIGACT Symp. on Principles of Programming Languages (POPL)'],
    'BALTZER':  ['Wireless Networks Journal published by Baltzer',
                 'Wireless Networks Journal published by Baltzer'],
    'TIT':      ['IEEE Transactions on Information Theory',
                 'IEEE Transactions on Information Theory'],
    'TCOMM':    ['IEEE Transactions on Communications',
                 'IEEE Transactions on Communications'],
    'TWC':      ['IEEE Transactions on Wireless Communications',
                 'IEEE Transactions on Wireless Communications'],
    'TCOMP':    ['IEEE Transactions on Computers',
                 'IEEE Transactions on Computers'],
    'TMC':      ['IEEE Transactions on Mobile Computing',
                 'IEEE Transactions on Mobile Computing'],
    'SIAMCOMP': ['SIAM Journal on Computing',
                 'SIAM Journal on Computing'],
    'EURASIP':  ['EURASIP Journal on Applied Signal Processing',
                 'EURASIP Journal on Applied Signal Processing'],
    'TSIG':     ['IEEE Transactions on Signal Processing',
                 'IEEE Transactions on Signal Processing'],
    'ICSE':     ['Proceedings of the IEEE/ACM International Conference on Software Engineering (ICSE)',
                 'Proc. IEEE/ACM Int. Conference on Software Engineering (ICSE)'],
    'ASE':      ['Proceedings of the IEEE/ACM International Conference on Automated Software Engineering (ASE)',
                 'Proc. IEEE/ACM Int. Conference on Automated Software Engineering (ASE)'],
    'FSE':      ['Proceedings of the ACM SIGSOFT Symposium on the Foundations of Software Engineering (FSE)',
                 'Proc. ACM SIGSOFT Symp. on the Foundations of Software Engineering (FSE)'],
}